### ISSUE TITLE
design the profile page for this site according to the theme.

### ISSUE THREAD

**Issue by Ashuto7h** [Dragsters/Artist-InMe#9]
design and develop a very nice UI  for profile page matching with the current theme of the site.

after running the server, go to ```localhost:3000/u``` and add a page for the profile section. 

Contribution Guidelines :
1.  Use the MDBootstrap framework for frontend designing.
2.  It should match the current theme of the site.
3.  UX should be nice and smooth.
4.  path for file should src/html/profile.html.
5.  for Javascript use src/js/profile.js

try to use material design concepts as much as possible.

**Comment by georgioupanayiotis** [comment]
Can you assign me this ?

**Comment by georgioupanayiotis** [comment]
Created the PR https://github.com/Dragsters/Artist-InMe/pull/12

**Comment by georgioupanayiotis** [comment]
Hello @Ashuto7h do you have the designs ?

**Comment by Ashuto7h** [comment]
> 
> 
> Hello @Ashuto7h do you have the designs ?

this is the design for profile page.

@georgioupanayiotis are you working on it ?


![Profile](https://user-images.githubusercontent.com/53266261/96571681-8308bd00-12e9-11eb-9bc4-2a90329194e9.png)
